### ISSUE TITLE
Fridge

### ISSUE THREAD

**Issue by MrLonely122** [kubakrakowiak/program_casino_fivem#11]
![Capture](https://user-images.githubusercontent.com/60043500/73116009-662b8e80-3efd-11ea-955d-81011bb1f0f3.JPG)

Getting this error every time I open the fridge menu and only the menu title shows up none of the options.

![Capture](https://user-images.githubusercontent.com/60043500/73116026-bacf0980-3efd-11ea-9c4b-48bc60703656.JPG)

**Comment by FlamingChilly** [comment]
We are also having this issue, does anyone have a fix yet for the fridges?

**Comment by kubakrakowiak** [comment]
Its not bug from program-casino-pack its bug from esx_menu_default

Fridges by default are empty, you have to fill stuff inside in the DB or make script to do it manually on server
