### ISSUE TITLE
Error in main.lua file from server

### ISSUE THREAD

**Issue by Kidoo96** [kubakrakowiak/program_casino_fivem#9]
I got error for nil value from this line
196: 
![image](https://user-images.githubusercontent.com/2369641/71559415-4d4acd00-2a66-11ea-9fc7-99a8dd5c71bf.png)

And cannot buy chips

**Comment by ali-exacute** [comment]
> 
> 
> I got error for nil value from this line
> 196:
> ![image](https://user-images.githubusercontent.com/2369641/71559415-4d4acd00-2a66-11ea-9fc7-99a8dd5c71bf.png)
> 
> And cannot buy chips

if you have updated version of ESX , you need to change things to work with it because there is no more `limit` thing for items , it is replaced with `weight`
